### ISSUE TITLE
About bind(Fragment)

### ISSUE THREAD

**Issue by whyalwaysmea** [zhihu/RxLifecycle#4]
I read the sample, it only support android.app.Fragment?
If i use android.support.v4.app.Fragment. What should I do?

**Comment by nekocode** [comment]
Check the [README](https://github.com/zhihu/RxLifecycle/blob/master/README.md#using-with-gradle):

> - (Optional) Add the below library if you need to support api 9 and later. Besides, if you already add support-v4 dependency, I will also suggest you to use this compact library, and then use the RxLifecycleCompact instead of the RxLifecycle.
> ```
> dependencies {
>     compile 'com.github.nekocode.rxlifecycle:rxlifecycle-compact:{lastest-version}'
> }
> ```
