### ISSUE TITLE
onComplete still be signalled after onDestroy

### ISSUE THREAD

**Issue by shangmingchao** [zhihu/RxLifecycle#5]
`onComplete` still be signalled after Activity's `onDestroy`. That means we cannot do some operations(such as dismiss dialog) in `onComplete` after the activity has been destroyed. 
So any suggestions for that situation?

**Comment by BCsl** [comment]
@shangmingchao  Because the use of [TakeUntil](http://reactivex.io/documentation/operators/takeuntil.html) operator , it will emit  onComplete single at last.

**Comment by nekocode** [comment]
The least release has resolved this issue.
